name: 🎱 Test deploy website on push

on:
  workflow_dispatch:

jobs:
  web-deploy:
    name: 🎉 Test deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: sv14944.xserver.jp
          username: chrs194399@xs363308.xsrv.jp
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: true
          dangerous-clean-slate: false
          server-dir: xs363308.xsrv.jp/public_html/
          local-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            **/.vscode/**
            **/node_modules/**
            xs363308.xsrv.jp/public_html/scss/**
